### ISSUE TITLE
Request: Curious About the Program's Inner Workings. More info?

### ISSUE THREAD

**Issue by yukihana-fan** [project-yukihana/Yukihana-patch#11]
I know this's to personnel to ask, but I didn't have another option. 

Well, as far as I understand, this `Yukihana-Patch` first made to patch `Telecord`. And it seems like `Fiddler Everywhere` patch is added later. Is it correct?

If so, this repo contains patches for both `FE` & `Telecord`, right? (`README` only mentions Telecord only though.)

And both of them use same hook?

Actually I couldn't understand this inner workings with source code cuz I'm actually a beginner to C and Reverse Engineering. 

So could you please spare some time and explain me how this work? or direct me to any resources that could help me learn more?

You must be busy, but any insight would be incredibly appreciated as I continue to learn.

**Comment by msojocs** [comment]
Your new ID & name moved me to fear; I can't answer you.

**Comment by yukihana-fan** [comment]
Sad. 😢
