### ISSUE TITLE
Auto-Work for upcoming Builds?

### ISSUE THREAD

**Issue by Dastano** [project-yukihana/Yukihana-patch#5]
Hey,

currently, I am using the IL2CPP Method to patch my Fiddler on every release, for Mac and Windows. I would like to know if your DLL works for upcoming releases.

I tried it on .11 but it errors out, so I assume it does not auto-patch the Functions and I have to modify it manually if I want to use the latest Version on day #1? 

I am fine with manually patching, but was just curious :)

```20:43:17.145 > Attempting to run server - 4 attempts left.
20:43:17.146 > Trying to start server at port [4716].
20:43:17.318 > Unable to start server process, closed with code: 252
20:43:17.318 > Attempt failed with Application port calculation failed. Contact support..
20:43:17.319 > Attempting to run server - 3 attempts left.
20:43:17.319 > Trying to start server at port [47256].
20:43:17.513 > Unable to start server process, closed with code: 252
20:43:17.513 > Attempt failed with Application port calculation failed. Contact support..
20:43:17.514 > Attempting to run server - 2 attempts left.
20:43:17.514 > Trying to start server at port [25746].
20:43:17.684 > Unable to start server process, closed with code: 252
20:43:17.685 > Attempt failed with Application port calculation failed. Contact support..
20:43:17.685 > Attempting to run server - 1 attempts left.
20:43:17.685 > Trying to start server at port [22753].
20:43:17.862 > Unable to start server process, closed with code: 252
20:43:17.862 > Attempt failed with Application port calculation failed. Contact support..
20:43:17.862 > Maximum number of attempts reached - quitting application.```

**Comment by msojocs** [comment]
Sorry, but this project utilizes a method that hooks into the Windows API, and currently, it does not support other platforms.

Therefore, you will need to use the older method on Mac.

**Comment by Dastano** [comment]
Hey,

Yeah I know, but on Windows I get the Error I posted.

When running the latest Version. That is why I asked, if the patch need to be updated for every new Fiddler Version?

I tried it on v5.11


PS: Do you know any debugger for Mac like DNSpy? Currently I patching the Mac Version under windows.

**Comment by Dastano** [comment]
I noticed the manual patch results in the same behavior.  The Issue relies on the main.xxxx.js file. 

https://api.getfiddler.com -> http://127.0.0.1:5678/api.getfiddler.com 

Results in:

WebServer>Fiddler.WebUi.exe --port=16225 --logDirectory=Path\To\Logs --verboseLogging=false --logMaxSize=4194304
Missing main app file!

Maybe they added a new protection in 5.11

**Comment by msojocs** [comment]
![image](https://github.com/project-yukihana/Yukihana-patch/assets/20937135/3d18e28b-cdc1-4f47-b68b-241fdfe08194)

The program works fine.

**Comment by msojocs** [comment]
I think we just need to update the file `patch.json`, when new version of fiddler published.

The patch program does not relate to a specify version of fiddler.

About dnSpy with mac: sorry I donot know.

**Comment by Dastano** [comment]
Yeah got it.

Can you guys check out: Offline license support on macOS since 5.12? Maybe this can be abused on MacOS.

Also, could you check out MAC for the Deep-Level Mode? There is System Proxy Mode. However the "cracked" Version cannot use it. 

The Issue lies in the Binary I believe. Since we use Electron. When I run the Original Binary, it works fine, but the Original Binary has a Self-Check I believe?

[Archiv.zip](https://github.com/user-attachments/files/15936613/Archiv.zip)

I attached Electron Binary and Fiddler Binary of MacOS on .12 maybe you can find a way how to use the Transparent Proxy Script with the patched Version.
